import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { Tool, ToolCategory, ToolState } from '@/types';

const initialTools: Tool[] = [
  // Calculators
  {
    id: 'basic-calculator',
    name: 'Basic Calculator',
    description: 'Basic arithmetic operations',
    category: ToolCategory.CALCULATORS,
    subcategory: 'Basic Math',
    capabilities: ['addition', 'subtraction', 'multiplication', 'division', 'percentage'],
    icon: 'Calculate',
    component: 'BasicCalculator',
  },
  {
    id: 'financial-calculator',
    name: 'Financial Calculator',
    description: 'Calculate loans, interest, and investments',
    category: ToolCategory.CALCULATORS,
    subcategory: 'Financial',
    capabilities: ['loan calculator', 'interest calculator', 'compound interest'],
    icon: 'AccountBalance',
    component: 'FinancialCalculator',
  },
  {
    id: 'scientific-calculator',
    name: 'Scientific Calculator',
    description: 'Advanced mathematical functions',
    category: ToolCategory.CALCULATORS,
    subcategory: 'Scientific',
    capabilities: ['trigonometry', 'logarithms', 'factorials'],
    icon: 'Functions',
    component: 'ScientificCalculator',
  },

  // Unit Converters
  {
    id: 'length-converter',
    name: 'Length Converter',
    description: 'Convert between different units of length',
    category: ToolCategory.UNIT_CONVERTERS,
    subcategory: 'Length',
    capabilities: ['meters', 'feet', 'inches', 'kilometers', 'miles'],
    icon: 'Straighten',
    component: 'LengthConverter',
  },
  {
    id: 'temperature-converter',
    name: 'Temperature Converter',
    description: 'Convert between Celsius, Fahrenheit, and Kelvin',
    category: ToolCategory.UNIT_CONVERTERS,
    subcategory: 'Temperature',
    capabilities: ['celsius', 'fahrenheit', 'kelvin'],
    icon: 'Thermostat',
    component: 'TemperatureConverter',
  },
  {
    id: 'weight-converter',
    name: 'Weight Converter',
    description: 'Convert between different units of weight',
    category: ToolCategory.UNIT_CONVERTERS,
    subcategory: 'Weight',
    capabilities: ['kilograms', 'pounds', 'ounces', 'grams'],
    icon: 'FitnessCenter',
    component: 'WeightConverter',
  },
  {
    id: 'area-converter',
    name: 'Area Converter',
    description: 'Convert between different units of area',
    category: ToolCategory.UNIT_CONVERTERS,
    subcategory: 'Area',
    capabilities: ['square meters', 'square feet', 'acres', 'hectares'],
    icon: 'CropFree',
    component: 'AreaConverter',
  },
  {
    id: 'volume-converter',
    name: 'Volume Converter',
    description: 'Convert between different units of volume',
    category: ToolCategory.UNIT_CONVERTERS,
    subcategory: 'Volume',
    capabilities: ['liters', 'gallons', 'cubic meters', 'fluid ounces'],
    icon: 'LocalDrink',
    component: 'VolumeConverter',
  },
  {
    id: 'time-converter',
    name: 'Time Converter',
    description: 'Convert between different units of time',
    category: ToolCategory.UNIT_CONVERTERS,
    subcategory: 'Time',
    capabilities: ['seconds', 'minutes', 'hours', 'days', 'years'],
    icon: 'Schedule',
    component: 'TimeConverter',
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between different world currencies',
    category: ToolCategory.UNIT_CONVERTERS,
    subcategory: 'Currency',
    capabilities: ['USD', 'EUR', 'GBP', 'JPY', 'exchange rates'],
    icon: 'CurrencyExchange',
    component: 'CurrencyConverter',
  },

  // Converters
  {
    id: 'base64-converter',
    name: 'Base64 Converter',
    description: 'Encode and decode Base64 strings',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Base64 Encode/Decode',
    capabilities: ['encode', 'decode'],
    icon: 'Code',
    component: 'Base64Converter',
  },
  {
    id: 'html-converter',
    name: 'HTML Encoder/Decoder',
    description: 'Encode and decode HTML entities',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Html Encode/Decode',
    capabilities: ['html encode', 'html decode'],
    icon: 'Html',
    component: 'HtmlConverter',
  },
  {
    id: 'url-converter',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URLs',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Url Encode/Decode',
    capabilities: ['url encode', 'url decode'],
    icon: 'Link',
    component: 'UrlConverter',
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between different case formats',
    category: ToolCategory.CONVERTERS,
    subcategory: 'String Case',
    capabilities: ['uppercase', 'lowercase', 'title case', 'camelCase', 'PascalCase', 'snake_case', 'kebab-case'],
    icon: 'TextFields',
    component: 'CaseConverter',
  },
  {
    id: 'base64-to-image',
    name: 'Base64 to Image',
    description: 'Convert Base64 strings to images',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Base64 to/from image',
    capabilities: ['base64 decode', 'image preview'],
    icon: 'Image',
    component: 'Base64ToImage',
  },
  {
    id: 'json-xml-converter',
    name: 'JSON to XML Converter',
    description: 'Convert between JSON and XML formats',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Json to/from XML',
    capabilities: ['json to xml', 'xml to json'],
    icon: 'DataObject',
    component: 'JsonXmlConverter',
  },
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert between decimal, binary, octal, and hexadecimal',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Decimal to/from Binary/Oct/Hex',
    capabilities: ['decimal', 'binary', 'octal', 'hexadecimal'],
    icon: 'Numbers',
    component: 'NumberBaseConverter',
  },

  // Validators
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description: 'Validate JSON syntax and structure',
    category: ToolCategory.VALIDATORS,
    subcategory: 'Json',
    capabilities: ['syntax validation', 'error detection'],
    icon: 'CheckCircle',
    component: 'JsonValidator',
  },
  {
    id: 'css-validator',
    name: 'CSS Validator',
    description: 'Validate CSS syntax and properties',
    category: ToolCategory.VALIDATORS,
    subcategory: 'CSS',
    capabilities: ['syntax validation', 'property validation'],
    icon: 'Css',
    component: 'CssValidator',
  },

  // Beautifiers
  {
    id: 'json-beautifier',
    name: 'JSON Beautifier',
    description: 'Format and beautify JSON code',
    category: ToolCategory.BEAUTIFIERS,
    subcategory: 'Json',
    capabilities: ['formatting', 'indentation', 'syntax highlighting'],
    icon: 'AutoFixHigh',
    component: 'JsonBeautifier',
  },
  {
    id: 'javascript-beautifier',
    name: 'JavaScript Beautifier',
    description: 'Format and beautify JavaScript code',
    category: ToolCategory.BEAUTIFIERS,
    subcategory: 'Javascript',
    capabilities: ['formatting', 'indentation', 'syntax highlighting'],
    icon: 'JavaScript',
    component: 'JavascriptBeautifier',
  },

  // Minifiers
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    description: 'Minify JSON by removing whitespace',
    category: ToolCategory.MINIFIERS,
    subcategory: 'Json',
    capabilities: ['compression', 'whitespace removal'],
    icon: 'Compress',
    component: 'JsonMinifier',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify CSS by removing whitespace and comments',
    category: ToolCategory.MINIFIERS,
    subcategory: 'CSS',
    capabilities: ['compression', 'whitespace removal'],
    icon: 'Compress',
    component: 'CssMinifier',
  },

  // Cryptography
  {
    id: 'hash-generator',
    name: 'Hashcode Generator',
    description: 'Generate various types of hash codes',
    category: ToolCategory.CRYPTOGRAPHY,
    subcategory: 'Hashcode Generators',
    capabilities: ['md5', 'sha1', 'sha256', 'sha512'],
    icon: 'Fingerprint',
    component: 'HashGenerator',
  },
  {
    id: 'aes-encryption',
    name: 'Encryption/Decryption (AES)',
    description: 'Encrypt and decrypt text using AES algorithm',
    category: ToolCategory.CRYPTOGRAPHY,
    subcategory: 'Encryption/Decryption',
    capabilities: ['aes-256', 'encrypt', 'decrypt', 'secure'],
    icon: 'Lock',
    component: 'AesEncryption',
  },
  {
    id: 'base64-encryption',
    name: 'Encryption/Decryption (Base64)',
    description: 'Simple Base64 encoding with optional password protection',
    category: ToolCategory.CRYPTOGRAPHY,
    subcategory: 'Encryption/Decryption',
    capabilities: ['base64', 'password protection', 'simple encryption'],
    icon: 'VpnKey',
    component: 'Base64Encryption',
  },
  {
    id: 'rsa-encryption',
    name: 'Encryption/Decryption (RSA)',
    description: 'RSA public/private key encryption and decryption',
    category: ToolCategory.CRYPTOGRAPHY,
    subcategory: 'Encryption/Decryption',
    capabilities: ['rsa', 'public key', 'private key', 'key generation'],
    icon: 'Key',
    component: 'RsaEncryption',
  },

  // Random Generators
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Password',
    capabilities: ['secure passwords', 'custom length', 'character sets'],
    icon: 'Password',
    component: 'PasswordGenerator',
  },
  {
    id: 'string-generator',
    name: 'Random String Generator',
    description: 'Generate random strings of specified length',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'String',
    capabilities: ['custom length', 'character sets'],
    icon: 'TextFormat',
    component: 'StringGenerator',
  },
  {
    id: 'color-generator',
    name: 'Color Generator',
    description: 'Generate random colors in various formats',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Color',
    capabilities: ['hex colors', 'rgb colors', 'hsl colors'],
    icon: 'Palette',
    component: 'ColorGenerator',
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate URL-friendly slugs from text',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Slug',
    capabilities: ['URL slugs', 'SEO friendly', 'customizable'],
    icon: 'Link',
    component: 'SlugGenerator',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate unique identifiers (UUIDs)',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'UUID',
    capabilities: ['v4 UUID', 'v1 UUID', 'various formats'],
    icon: 'Key',
    component: 'UuidGenerator',
  },
  {
    id: 'lorem-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate Lorem Ipsum placeholder text',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Lorem Ipsum',
    capabilities: ['words', 'sentences', 'paragraphs'],
    icon: 'Article',
    component: 'LoremGenerator',
  },
  {
    id: 'number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers within a range',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Number',
    capabilities: ['integers', 'decimals', 'statistics'],
    icon: 'Numbers',
    component: 'NumberGenerator',
  },
  {
    id: 'name-generator',
    name: 'Name Generator',
    description: 'Generate random names for people and companies',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Name',
    capabilities: ['first names', 'full names', 'usernames', 'companies'],
    icon: 'Person',
    component: 'NameGenerator',
  },

  // String Utilities
  {
    id: 'string-reverse',
    name: 'String Reverser',
    description: 'Reverse the order of characters in text',
    category: ToolCategory.STRING_UTILITIES,
    subcategory: 'Reverse string',
    capabilities: ['reverse text', 'reverse words'],
    icon: 'SwapHoriz',
    component: 'StringReverser',
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, and lines in text',
    category: ToolCategory.STRING_UTILITIES,
    subcategory: 'Count word',
    capabilities: ['word count', 'character count', 'line count'],
    icon: 'Numbers',
    component: 'WordCounter',
  },
  {
    id: 'string-escape',
    name: 'String Escape Utilities',
    description: 'Escape and unescape strings for various formats',
    category: ToolCategory.STRING_UTILITIES,
    subcategory: 'Escape',
    capabilities: ['JSON escape', 'HTML escape', 'URL encode', 'SQL escape'],
    icon: 'Security',
    component: 'StringEscapeUtilities',
  },
  {
    id: 'quote-utilities',
    name: 'Quote Utilities',
    description: 'Add, remove, or convert quotes in text',
    category: ToolCategory.STRING_UTILITIES,
    subcategory: 'Quotes',
    capabilities: ['add quotes', 'remove quotes', 'convert quotes'],
    icon: 'FormatQuote',
    component: 'QuoteUtilities',
  },
  {
    id: 'text-joiner',
    name: 'Text Joiner',
    description: 'Join multiple lines of text with custom separators',
    category: ToolCategory.STRING_UTILITIES,
    subcategory: 'Join',
    capabilities: ['join text', 'custom separator', 'prefix/suffix'],
    icon: 'CallMerge',
    component: 'TextJoiner',
  },
  {
    id: 'text-splitter',
    name: 'Text Splitter',
    description: 'Split text by delimiter, length, or regex pattern',
    category: ToolCategory.STRING_UTILITIES,
    subcategory: 'Split',
    capabilities: ['split by delimiter', 'split by length', 'regex split'],
    icon: 'CallSplit',
    component: 'TextSplitter',
  },
  {
    id: 'slug-generator-string',
    name: 'Slug Generator',
    description: 'Convert text to URL-friendly slugs',
    category: ToolCategory.STRING_UTILITIES,
    subcategory: 'Slug',
    capabilities: ['URL slugs', 'SEO friendly', 'custom options'],
    icon: 'Link',
    component: 'SlugGenerator',
  },

  // Miscellaneous
  {
    id: 'whitespace-remover',
    name: 'Whitespace Remover',
    description: 'Remove duplicate whitespace and empty lines',
    category: ToolCategory.MISCELLANEOUS,
    subcategory: 'Remove duplicate whitespace',
    capabilities: ['remove whitespace', 'clean text'],
    icon: 'CleaningServices',
    component: 'WhitespaceRemover',
  },
  {
    id: 'ascii-art-generator',
    name: 'ASCII Art Generator',
    description: 'Convert text to ASCII art',
    category: ToolCategory.MISCELLANEOUS,
    subcategory: 'ASCII Art',
    capabilities: ['text to ascii', 'various fonts'],
    icon: 'TextFormat',
    component: 'AsciiArtGenerator',
  },

  // Additional Converters (placeholders for missing subcategories)
  {
    id: 'json-csv-converter',
    name: 'JSON to/from CSV Converter',
    description: 'Convert between JSON and CSV formats',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Json to/from CSV',
    capabilities: ['json to csv', 'csv to json', 'custom delimiters'],
    icon: 'TableChart',
    component: 'JsonCsvConverter',
  },
  {
    id: 'html-markdown-converter',
    name: 'HTML to/from Markdown Converter',
    description: 'Convert between HTML and Markdown formats',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Html to/from Markdown',
    capabilities: ['html to markdown', 'markdown to html', 'syntax highlighting'],
    icon: 'Code',
    component: 'HtmlMarkdownConverter',
  },
  {
    id: 'general-encryption',
    name: 'General Encryption/Decryption',
    description: 'Various encryption and decryption methods',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Encryption/Decryption',
    capabilities: ['multiple algorithms', 'secure encryption'],
    icon: 'Security',
    component: 'GeneralEncryption',
  },

  // Additional Validators (placeholders for missing subcategories)
  {
    id: 'javascript-validator',
    name: 'JavaScript Validator',
    description: 'Validate JavaScript code syntax',
    category: ToolCategory.VALIDATORS,
    subcategory: 'Javascript',
    capabilities: ['syntax validation', 'error detection'],
    icon: 'Code',
    component: 'JavascriptValidator',
  },

  // Additional Beautifiers (placeholders for missing subcategories)
  {
    id: 'csharp-beautifier',
    name: 'C# Beautifier',
    description: 'Format and beautify C# code',
    category: ToolCategory.BEAUTIFIERS,
    subcategory: 'C#',
    capabilities: ['formatting', 'indentation', 'syntax highlighting'],
    icon: 'Code',
    component: 'CsharpBeautifier',
  },
  {
    id: 'sql-beautifier',
    name: 'SQL Beautifier',
    description: 'Format and beautify SQL queries',
    category: ToolCategory.BEAUTIFIERS,
    subcategory: 'SQL',
    capabilities: ['formatting', 'indentation', 'keyword highlighting'],
    icon: 'Storage',
    component: 'SqlBeautifier',
  },
  {
    id: 'css-beautifier',
    name: 'CSS Beautifier',
    description: 'Format and beautify CSS code',
    category: ToolCategory.BEAUTIFIERS,
    subcategory: 'CSS',
    capabilities: ['formatting', 'indentation', 'property organization'],
    icon: 'Css',
    component: 'CssBeautifier',
  },
  {
    id: 'typescript-beautifier',
    name: 'TypeScript Beautifier',
    description: 'Format and beautify TypeScript code',
    category: ToolCategory.BEAUTIFIERS,
    subcategory: 'Typescript',
    capabilities: ['formatting', 'indentation', 'syntax highlighting'],
    icon: 'Code',
    component: 'TypescriptBeautifier',
  },

  // Additional Minifiers (placeholders for missing subcategories)
  {
    id: 'javascript-minifier',
    name: 'JavaScript Minifier',
    description: 'Minify JavaScript by removing whitespace and comments',
    category: ToolCategory.MINIFIERS,
    subcategory: 'Javascript',
    capabilities: ['compression', 'whitespace removal', 'comment removal'],
    icon: 'Compress',
    component: 'JavascriptMinifier',
  },

  // Fix Cryptography subcategories
  {
    id: 'general-encryption-crypto',
    name: 'Encryption/Decryption Tools',
    description: 'General encryption and decryption utilities',
    category: ToolCategory.CRYPTOGRAPHY,
    subcategory: 'Encryption/Decryption',
    capabilities: ['multiple algorithms', 'key management'],
    icon: 'Lock',
    component: 'GeneralEncryptionCrypto',
  },

  // Additional Random Generators (placeholders for missing subcategories)
  {
    id: 'digit-generator',
    name: 'Random Digit Generator',
    description: 'Generate random single digits',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Digit',
    capabilities: ['single digits', 'multiple digits', 'custom ranges'],
    icon: 'Numbers',
    component: 'DigitGenerator',
  },
  {
    id: 'decimal-generator',
    name: 'Random Decimal Generator',
    description: 'Generate random decimal numbers',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Decimal',
    capabilities: ['decimal precision', 'range control'],
    icon: 'Numbers',
    component: 'DecimalGenerator',
  },
  {
    id: 'character-generator',
    name: 'Random Character Generator',
    description: 'Generate random individual characters',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Character',
    capabilities: ['letters', 'symbols', 'unicode'],
    icon: 'TextFormat',
    component: 'CharacterGenerator',
  },
  {
    id: 'phrase-generator',
    name: 'Random Phrase Generator',
    description: 'Generate random phrases and expressions',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Phrase',
    capabilities: ['meaningful phrases', 'custom length'],
    icon: 'ChatBubble',
    component: 'PhraseGenerator',
  },
  {
    id: 'paragraph-generator',
    name: 'Random Paragraph Generator',
    description: 'Generate random paragraphs of text',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Paragraph',
    capabilities: ['paragraphs', 'various topics'],
    icon: 'Article',
    component: 'ParagraphGenerator',
  },
  {
    id: 'page-generator',
    name: 'Random Page Generator',
    description: 'Generate random full pages of content',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Page',
    capabilities: ['full pages', 'structured content'],
    icon: 'Description',
    component: 'PageGenerator',
  },
  {
    id: 'image-generator',
    name: 'Random Image Generator',
    description: 'Generate random placeholder images',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Image',
    capabilities: ['placeholder images', 'custom dimensions'],
    icon: 'Image',
    component: 'ImageGenerator',
  },
  {
    id: 'ip-generator',
    name: 'Random IP Address Generator',
    description: 'Generate random IP addresses',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'IP Address',
    capabilities: ['ipv4', 'ipv6', 'private ranges'],
    icon: 'Router',
    component: 'IpGenerator',
  },
  {
    id: 'datetime-generator',
    name: 'Random DateTime Generator',
    description: 'Generate random dates and times',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'DateTime',
    capabilities: ['random dates', 'time ranges', 'various formats'],
    icon: 'Schedule',
    component: 'DateTimeGenerator',
  },

  // Additional String Utilities (placeholders for missing subcategories)
  {
    id: 'string-case-utility',
    name: 'String Case Converter',
    description: 'Convert text between different cases',
    category: ToolCategory.STRING_UTILITIES,
    subcategory: 'String Case',
    capabilities: ['uppercase', 'lowercase', 'camelCase', 'snake_case'],
    icon: 'TextFormat',
    component: 'StringCaseUtility',
  },

  // Additional Miscellaneous (placeholders for missing subcategories)
  {
    id: 'empty-lines-remover',
    name: 'Empty Lines Remover',
    description: 'Remove empty lines from text',
    category: ToolCategory.MISCELLANEOUS,
    subcategory: 'Remove empty lines',
    capabilities: ['remove empty lines', 'clean formatting'],
    icon: 'CleaningServices',
    component: 'EmptyLinesRemover',
  },

  // 10 High-Value New Tools
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text, URLs, or other data',
    category: ToolCategory.CONVERTERS,
    subcategory: 'QR Code Generation',
    capabilities: ['text to qr', 'url to qr', 'custom size', 'error correction'],
    icon: 'QrCode2',
    component: 'QrCodeGenerator',
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress and optimize images for web use',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Image Processing',
    capabilities: ['jpeg compression', 'png optimization', 'resize', 'format conversion'],
    icon: 'Compress',
    component: 'ImageCompressor',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and build regular expressions with live preview',
    category: ToolCategory.STRING_UTILITIES,
    subcategory: 'Regex Tools',
    capabilities: ['pattern testing', 'match highlighting', 'regex builder'],
    icon: 'Search',
    component: 'RegexTester',
  },
  {
    id: 'json-path-extractor',
    name: 'JSON Path Extractor',
    description: 'Extract values from JSON using JSONPath queries',
    category: ToolCategory.CONVERTERS,
    subcategory: 'JSON Tools',
    capabilities: ['jsonpath queries', 'value extraction', 'path finding'],
    icon: 'AccountTree',
    component: 'JsonPathExtractor',
  },
  {
    id: 'cron-builder',
    name: 'Cron Expression Builder',
    description: 'Build and validate cron expressions for scheduling',
    category: ToolCategory.MISCELLANEOUS,
    subcategory: 'Time Scheduling',
    capabilities: ['cron builder', 'schedule validation', 'next runs preview'],
    icon: 'Schedule',
    component: 'CronBuilder',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Query Formatter',
    description: 'Format and beautify SQL queries',
    category: ToolCategory.BEAUTIFIERS,
    subcategory: 'SQL',
    capabilities: ['sql formatting', 'syntax highlighting', 'query optimization'],
    icon: 'Storage',
    component: 'SqlFormatter',
  },
  {
    id: 'placeholder-image-generator',
    name: 'Placeholder Image Generator',
    description: 'Generate placeholder images for development',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Image',
    capabilities: ['custom dimensions', 'text overlay', 'color schemes'],
    icon: 'Image',
    component: 'PlaceholderImageGenerator',
  },
  {
    id: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    description: 'Create and format markdown tables easily',
    category: ToolCategory.CONVERTERS,
    subcategory: 'Markdown Tools',
    capabilities: ['table creation', 'csv to table', 'alignment options'],
    icon: 'TableChart',
    component: 'MarkdownTableGenerator',
  },
  {
    id: 'font-pair-previewer',
    name: 'Font Pair Previewer',
    description: 'Preview and test font combinations',
    category: ToolCategory.MISCELLANEOUS,
    subcategory: 'Design Tools',
    capabilities: ['font pairing', 'preview text', 'google fonts'],
    icon: 'FontDownload',
    component: 'FontPairPreviewer',
  },
  {
    id: 'api-mock-generator',
    name: 'API Response Mock Generator',
    description: 'Generate mock API responses for testing',
    category: ToolCategory.RANDOM_GENERATORS,
    subcategory: 'Developer Tools',
    capabilities: ['json responses', 'data types', 'nested objects'],
    icon: 'Api',
    component: 'ApiMockGenerator',
  },
];

const initialState: ToolState = {
  selectedCategory: null,
  searchQuery: '',
  tools: initialTools,
};

const toolsSlice = createSlice({
  name: 'tools',
  initialState,
  reducers: {
    setSelectedCategory: (state: ToolState, action: PayloadAction<ToolCategory | null>) => {
      state.selectedCategory = action.payload;
    },
    setSearchQuery: (state: ToolState, action: PayloadAction<string>) => {
      state.searchQuery = action.payload;
    },
    addTool: (state: ToolState, action: PayloadAction<Tool>) => {
      state.tools.push(action.payload);
    },
    removeTool: (state: ToolState, action: PayloadAction<string>) => {
      state.tools = state.tools.filter((tool: Tool) => tool.id !== action.payload);
    },
  },
});

export const { setSelectedCategory, setSearchQuery, addTool, removeTool } = toolsSlice.actions;

// Export tools data for static generation
export { initialTools as allTools };

export default toolsSlice.reducer;
